---
title: ""
---

# Καλωσορίσατε στην iGem Thrace

\

### Ποιοί είμαστε 

####### &emsp; &emsp; Η iGEM Thrace είναι μια διεπιστημονική ομάδα φοιτητών από την περιοχή της Θράκης, που συμμετέχει στον διεθνή διαγωνισμό iGEM (International Genetically Engineered Machine).    

####### &emsp; &emsp; Η iGEM THRACE δημιουργήθηκε το 2021 και απο τότε εκπροσωπεί το Δημοκρίτειο Πανεπιστήμιο Θράκης στο παγκόσμιο διαγωνισμός συνθετικής βιολογίας. Έχοντας ήδη κατακτήσει ένα χρυσό και ενα ασημένιο μετάλλιο, η ομάδα μας συνεχίζει το το ταξίδι της στον κόσμο της βιολογίας. 

\

### Η Αποστολή μας 

####### &emsp; &emsp; Η ομάδα της iGem Thrace στοχεύει στην γεφύρωση του όλο και αυξανόμενου χάσματος μεταξύ της βιοτεχνολογίας και της κοινωνίας. Αξιοποιώντας την συνθετική βιολογία, λύνουμε προβλήματα που αφορούν όλους. 

\


* ### Οι χορηγίες μας επιτρέπουν:
    + Την ανάπτυξη καινοτόμων ερευνητικών έργων.
    + Τη συμμετοχή μας στον διαγωνισμό iGEM.
    + Την εκπαίδευση του επιστημονικού προσωπικού της iGem Thrace.
    + Την λήψη πρωτοβουλιών κοινωνικού και πολιτιστικού χαρακτήρα στην Αλεξανδρούπολη.


\

# Ελάτε Μαζί μας
###### Είτε είστε εταιρεία, ίδρυμα ή άτομο, η υποστήριξή σας έχει μεγάλη σημασία.  Γίνετε χορηγός και να συμβάλετε σε αυτή τη μοναδική πρωτοβουλία.

*  ###### Μαζί, μπορούμε να κάνουμε τη διαφορά!


\
\
\
\


##### Σας ευχαριστούμε που στηρίζετε την αποστολή μας και γίνεστε μέρος αυτής της προσπάθειας να φέρουμε την αλλαγή.

